### PR TITLE
Implement Wuffs integration for benchmarks

### PR DESCRIPTION
**Pull request by pjanx**
Some characteristics:
 - can't do gamma correction,
 - doesn't parse all standard chunks,
 - doesn't require zlib,
 - cannot encode,
 - doesn't support APNG,
 - _beats everyone on speed_.

I _think_ it can decode from a stream, and read images progressively, but I'm not sure.

### CODE REVIEW

**Comment by pjanx** [comment]
Note that this comparison has already [been made](https://nigeltao.github.io/blog/2021/fastest-safest-png-decoder.html#appendix-benchmark-numbers) and [can be reproduced separately](https://github.com/google/wuffs/blob/v0.3.0-beta.9/test/c/mimiclib/png.c).

**Comment by pjanx** [comment]
You might consider reviewing Nigel's comments in https://github.com/google/wuffs/blob/v0.3.0-beta.9/test/c/mimiclib/png.c#L40

**Comment by randy408** [comment]
> You might consider reviewing Nigel's comments in https://github.com/google/wuffs/blob/v0.3.0-beta.9/test/c/mimiclib/png.c#L40

> libspng calculates but does not verify the CRC-32 checksum on the final IDAT chunk

This is true in practice, it's delayed until `spng_get_<chunk>()` or `spng_decode_chunks()` which is usually not called.

**Comment by randy408** [comment]
Have you checked the numbers? I expected a wider gap, not 15-20%
<details>
  <summary>Click to expand!</summary>

```
1/7 spngt:decode / image_decode OK              7.45s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/large_rgb8.png
----------------------------------- output -----------------------------------
libpng:    270738 usec
spng:      172952 usec
stb_image: 373713 usec
lodepng:   332696 usec
wuffs:     151858 usec
------------------------------------------------------------------------------

2/7 spngt:decode / image_decode OK              8.39s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/large_rgba8.png
----------------------------------- output -----------------------------------
libpng:    332811 usec
spng:      207514 usec
stb_image: 377592 usec
lodepng:   359197 usec
wuffs:     174164 usec
------------------------------------------------------------------------------

3/7 spngt:decode / image_decode OK              0.54s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/large_palette.png
----------------------------------- output -----------------------------------
libpng:    19481 usec
spng:      15968 usec
stb_image: 17517 usec
lodepng:   23741 usec
wuffs:     11383 usec
------------------------------------------------------------------------------

4/7 spngt:decode / image_decode OK              1.33s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/medium_rgb8.png
----------------------------------- output -----------------------------------
libpng:    41071 usec
spng:      27828 usec
stb_image: 60325 usec
lodepng:   54489 usec
wuffs:     22605 usec
------------------------------------------------------------------------------

5/7 spngt:decode / image_decode OK              1.81s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/medium_rgba8.png
----------------------------------- output -----------------------------------
libpng:    59323 usec
spng:      37196 usec
stb_image: 65825 usec
lodepng:   66994 usec
wuffs:     30657 usec
------------------------------------------------------------------------------

6/7 spngt:decode / image_decode OK              0.14s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/small_rgb8.png
----------------------------------- output -----------------------------------
libpng:    3848 usec
spng:      2516 usec
stb_image: 5662 usec
lodepng:   4851 usec
wuffs:     1903 usec
------------------------------------------------------------------------------

7/7 spngt:decode / image_decode OK              0.16s
spngt/build/spngt spngt/build/../subprojects/benchmark_images/small_rgba8.png
----------------------------------- output -----------------------------------
libpng:    4970 usec
spng:      3180 usec
stb_image: 6102 usec
lodepng:   5802 usec
wuffs:     2487 usec
------------------------------------------------------------------------------
```
</details>

**Comment by pjanx** [comment]
I'm getting vaguely similar results but have given up on _visualising_ the differences.

A tiny bit of it could be RGBA vs BGRA where Nigel's benchmark inflicts a penalty on spng.

In general, the benchmarks could be compared. But who cares, I just wanted that bar chart on the web site to be complete.

**Comment by randy408** [comment]
The chart hasn't been updated for about a year, since then zlib-ng had its first stable release, I should really integrate and benchmark it first before moving on to updating the chart.

@nigeltao do you think [these benchmarks results](https://github.com/libspng/spngt/pull/4#issuecomment-930054487) including wuffs are accurate? Can it get any faster than this? RGBA8 (PNG channel order) is the output format in all cases, source format is indicated by the filename. The image set is kind of limited and filter-heavy but the paletted image has no filtering and the speedup is around the same.

**Comment by nigeltao** [comment]
> do you think these benchmarks results including wuffs are accurate?

Those benchmark ratios look roughly plausible, in that my rule of thumb was that Wuffs was 2.0x to 2.5x libpng performance and IIRC libspng was between the two.

Having said that, I would have expected a slightly wider gap too, although that could very well be different hardware and a different set of images. One thing is that Wuffs might have a slightly higher 'fixed cost' and lower 'variable (per-pixel) cost', so the ratios might widen the larger (in pixel area) the test images are...


> - can't do gamma correction,
> - doesn't support APNG,

FWIW, these are https://github.com/google/wuffs/issues/39 and https://github.com/google/wuffs/issues/41


> I think it can decode from a stream, and read images progressively, but I'm not sure.

Yeah, Wuffs can decode from a stream. For an example, the `example/imageviewer/imageviewer.cc` in the Wuffs repository calls `wuffs_aux::DecodeImage` and the implementation at the bottom of `internal/cgen/auxiliary/image.cc` uses a 32 KiB buffer when reading from a file (as opposed to reading a contiguous chunk of memory containing the entire input).

**Comment by randy408** [comment]
Thanks @nigeltao @pjanx I'll be updating the comparison table/chart at some point, still have to add zlib-ng somehow to the project (Meson's CMake interop is not quite there yet), will probably add times with miniz too.

**Pull request merged**
